# deployment.yaml
apiVersion: apps/tirvaka1
kind: Deployment
metadata:
  name: argocd-app
  namespace: argocd-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: nginx:latest
        ports:
        - containerPort: 80

