# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argocd-app
  namespace: argocd-app
spec:
  selector:
    app: argocd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

